---

- hosts: all
  become: true
  tasks:
  

  - name: update and install apache and php packages
    package: 
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"
