---

- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates on Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" 

  - name: upgrade all package on ubuntu
    tags: always
    apt:
      upgrade: dist
    when: ansible_distribution == "Ubutnu"


  - name: update and install apache and php packages
    tags: apache,apache2,ubuntu
    package:
      name:
         - "{{ apache_package_name }}"
         - "{{ php_package_name }}"
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: start http
    tags: apache,apache2
    service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes
    when: ansible_distribution == "Ubuntu"


  - name: copy defautl html file for site
    tags: always
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
 


- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations
