---

- hosts: web_servers
  become: true
  pre_tasks:
 
  - name: install updates on Ubuntu
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: upgrade all package on ubuntu
    tags: always
    apt:
      upgrade: dist
    when: ansible_distribution == "Ubutnu"

  - name: copy defautl html file for site
    tags: always
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: update and install apache and php packages
    tags: apache,apache2,ubuntu
    package: 
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"
