- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM+InM7PftE1IBY0Rk58ZGM7hvgY8GH7SpHLKUcMK1ME Ansible"
    
- name: change e-mail add for admin
  tags: apache,apache2
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: 'ServerAdmin'
    line: ServerAdmin somebody@somewhere.org
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache


- name: generat sshd_config file form template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
